apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: create-cluster-
spec:
  workflowTemplateRef:
    name: cluster-templates
<<<<<<< HEAD
  entrypoint: elasticsearch-8-18-single-node
  arguments:
    parameters:
      - name: cluster-name
        value: "elasticsearch-8-18-single-node"
=======
  entrypoint: opensearch-3-1-single-node
  arguments:
    parameters:
      - name: cluster-name
        value: "source-opensearch-3-1-test-cluster"
>>>>>>> origin/main
      - name: namespace
        value: "ma"
      - name: replicas
        value: "3"
