elasticsearch:
  # ES 1.5 configuration using ARM-compatible image
  imageTag: "1.5.2"
  image: "carlchinatomby/elasticsearch:1.5.2-arm64"
  antiAffinity: "soft"
  esJavaOpts: "" # not used by ES 1.5; empty it to avoid confusion
  protocol: http
  replicas: 1 # Set replicas to the number of nodes you want in the cluster (e.g., 3)
  createCert: false
  sysctlInitContainer:
    enabled: false
  esConfig:
    elasticsearch.yml: |
      bootstrap.system_call_filter: false
      xpack.security.enabled: false
      network.host: 0.0.0.0
  extraEnvs:
    - name: "cluster.initial_master_nodes" # Replace this setting that is added by chart with "" since this setting is not supported in ES 1.x
      value: ""
    - name: "node.roles" # Replace this setting that is added by chart with "" since this setting is not supported in ES 1.x
      value: ""
    - name: "path.repo"
      value: "/snapshot"
  extraVolumes:
    - name: snapshot-volume
      persistentVolumeClaim:
        claimName: snapshot-volume-pvc  # Should match existing snapshot volume PVC
  extraVolumeMounts:
    - name: snapshot-volume
      mountPath: /snapshot
