elasticsearch:
  imageTag: "5.6.16"
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  antiAffinity: "soft"
  esJavaOpts: "-Xmx2g -Xms2g"
  protocol: http
  replicas: 1 # Set replicas to the number of nodes you want in the cluster
  createCert: false
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=3s"
  readinessProbe:
    failureThreshold: 5
    successThreshold: 2
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "3"
  esConfig:
    elasticsearch.yml: |
      bootstrap.system_call_filter: false
      xpack.security.enabled: false
      xpack.monitoring.enabled: false
      xpack.ml.enabled: false
      network.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      
      # Bulk indexing optimizations
      # index_buffer_size set to 25% to allow 512MB of 2GB heap
      indices.memory.index_buffer_size: 25% 
      thread_pool.bulk.queue_size: 1000
      thread_pool.bulk.size: 4
      indices.recovery.max_bytes_per_sec: 50mb
      
      # Circuit breaker settings
      indices.breaker.total.limit: 70%
      indices.breaker.request.limit: 60%
      indices.breaker.fielddata.limit: 60%
      
      # Memory optimization
      indices.memory.min_index_buffer_size: 24mb
      indices.memory.max_index_buffer_size: 512mb
  extraEnvs:
    - name: "cluster.initial_master_nodes" # Replace this setting that is added by chart with "" since this setting is not supported in ES 5.x
      value: ""
    - name: "node.roles" # Replace this setting that is added by chart with "" since this setting is not supported in ES 5.x
      value: ""
    - name: "path.repo"
      value: "/snapshot"
  extraVolumes:
    - name: snapshot-volume
      persistentVolumeClaim:
        claimName: snapshot-volume-pvc  # Should match existing snapshot volume PVC
  extraVolumeMounts:
    - name: snapshot-volume
      mountPath: /snapshot
  persistence:
    enabled: false