opensearch:
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: myStrongPassword123!
  singleNode: true
  persistence:
    enabled: false
  maxUnavailable: null

masterService:
  name: target-master

podDisruptionBudget:
  name: target-master-pdb
